Attempt to fix missing class error by not using tree artifacts for bootclasspath
A few times a year across many thousands of builds we encounter a rare
error about the `DumpPlatformClassPath` class being missing. Our Bazel
setup uses dynamic execution, builds without the bytes, remote execution
+ remote caching, and path mapping.

The error we encounter is as follows:
```
Error: Could not find or load main class DumpPlatformClassPath
Caused by: java.lang.ClassNotFoundException: DumpPlatformClassPath
```

I'm guessing that this is happening due to some kind of Bazel bug that
happens with our Bazel setup and tree artifacts, i.e.,
declare_directory.

Best I can tell this is happening because the
`DumpPlatformClassPath.class` file is somehow not materializing
correctly. I'm not 100% confident about that, but it's my leading
hypothesis at this point in time.

This commit changes the actions in `bootclasspath.bzl` to not rely on
tree artifacts. Instead, they rely JDK 11+'s ability to launch
single-file programs (introduced in JEP 330). This avoids the `javac`
action and `declare_directory` previously required to compile
`DumpPlatformClassPath`.

Problem is this makes rules_java not compatible with JDK's older than
11.